- name: update vulnerable packages
  hosts: '@@HOSTS@@'
  vars:
    insights_issues: '@@ISSUES@@'
    insights_signature_exclude: /hosts,/vars/insights_issues,/vars/insights_signature
    insights_signature: !!binary |
      ZnNReHdHaFNaZ0lqZ2pMd0MyQWs2UHpIMVZEd2hsdlFiL1ZQdkNPUGowMHBmbUhIZzRRS1lMTUdu
      NHU4cTRyVTdBQ042ekhabm9sYzhFSW1udVFOa3dZWU0rN0hhVGhIbFYwTlgwRHJERWxaWWI0ekZK
      M3hjTDVGc1FLSk8vcVVLc0JpcWRUazFaT0xZeUprQVRwRGhKdW5JaURNOEo3WXFIOVJxa3ErWVRl
      eXY1eWZKVU56MlhCM1kzb0JBejhHSmdyZ0NDSXZKYzBmSnU0ZWJHUXNtOU9zN2NUdmk1ZHhVd3Br
      UjI4T2lyYWVhcm1tSXhDUWtFYktuNVpoTjBJT2hsNytHWkVyVkZKcTB6cHdDMzRSdEw4RkJORXV3
      UVhnOFdOTDAxb1c2ZG8rWUxNVFJLcjA4b3pOaGNOQjVTT3RMWW4rQzhTdWdwVVVyMEljaVJUNkRB
      PT0=
  become: true
  tasks:
    - name: check for update
      shell: '{{ ansible_facts[''pkg_mgr''] }} check-update -q --cve {{ insights_issues }}'
      check_mode: false
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100
      args:
        warn: false
    - when: check_out.rc == 100
      name: upgrade package
      shell: '{{ ansible_facts[''pkg_mgr''] }} upgrade -v -y --cve {{ insights_issues }}'
      args:
        warn: false
    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true
