- name: update vulnerable packages
  hosts: '@@HOSTS@@'
  vars:
    insights_issues: '@@ISSUES@@'
    insights_signature_exclude: /hosts,/vars/insights_issues,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS0NtbFJSWHBDUVVGQ1EwRkJa
      RVpwUlVWQmMzVTJTbWsxYkhoUlpqTlRkVTgyT1U0ek1WWXdZMUU1U1RCR1FXMUNVMFZ0VFVGRFoy
      dFJPVTR6TVZZd1kxRUtPVWt3TVVWUlppOVpNbFJaYW1jNU5FVTBSV3gyV0M5a00xZHVNVlJ1WWtk
      U1RuSjViVVpLUVhFM2MxVmFOVmRwZWtaMGN5OHdOVmM1ZFhOSlFubDJPQXBQWVVSbWIybzVhelY1
      U1dzeVVFRXlZU3QxZWpWRVNqZE9lalpxVGpWSGRuZDRhR2MyTmt4NmJFdFNiVXBsT0RsdGMzUklZ
      bEV4TXpOUFFUZFBlamhMQ2xkQ1FsQjFWVTAyZGtjMVpGSkNka1JwWkRWemRuVnZXVEZHTHpacldu
      b3plVlphTm5GWmRETXlPR0Z1SzJ4M05VMU1ibXh5UjFWU2NYbGFlVWRwUzJ3S1kxaDBlblZOVW1O
      VGNpOTNabEEzYmpsQmFtNXNhRlZDZFUxRVYydENWR0ZoVG5CeWRtWktibmw2UkV4UE5UUlFWSGRH
      YmtOdWVUbFJXR2xMTWtWdFJncEdkekpuV1dOblQwWjJhMngzY0RodFdWZHFOVWxIVmtkWVJtOUlT
      MU00Y21VeFZtWlpPWGQ2YzFod1VqWXhNekZDT1ZsaWFYRlpZVkpFUVM5UlNYVnhDakF6UXpWbk5V
      ZElNMjlEVURkQlNXczBlUzk0ZG1oNGQwNHJTMVZJWnowOUNqMTFlRzF5Q2kwdExTMHRSVTVFSUZC
      SFVDQlRTVWRPUVZSVlVrVXRMUzB0TFFvPQ==
  become: true
  tasks:
    - name: check for update
      shell: '{{ ansible_facts[''pkg_mgr''] }} check-update -q --cve {{ insights_issues }}'
      check_mode: false
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100
      args:
        warn: false
    - when: check_out.rc == 100
      name: upgrade package
      shell: '{{ ansible_facts[''pkg_mgr''] }} upgrade -v -y --cve {{ insights_issues }}'
      args:
        warn: false
    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true
