- name: update vulnerable packages
  hosts: '@@HOSTS@@'
  vars:
    insights_issues: '@@ISSUES@@'
    insights_signature_exclude: /hosts,/vars/insights_issues,/vars/insights_signature
    insights_signature: !!binary |
      VXdFR3AxWnhta1Y5MktWTHBwVHFhQWRPVWtKMXZ6bjNoTVE5Q1diWDRSLzRIUlRtY1hnTVFBdXZW
      Y0l5TEpVZUFFWXBCZGxIR2h2M1pCQmd3Mng4MTZWU1c5ZVl3SWVGdnJ2UVErNWVUUlV6ZmU4R01z
      dUFVaFJYWnJuT1oycmxsUEZpVm8vK2xHZDVBL0hJWU9wM01xNkFiSGlHOE5OSXVleGxzaU00M0VK
      S3FMbFRiUEUrUnVUa3RhWG9uRmdHenFqVmg5WDBCNXVKS2JSR1BUUnlmbUt3MitvZTh1RTJaZkh6
      TnBMcE5XaXJxd2hMZjdFMDUyK3A3NWl5TkUvRkMxQm9zS0d0QmZTZjdPVlBrNU9QU013UTVxeDFl
      aFArd2VRRjIvNFJ2MUtLZWF3L3BFbFppc0xNdjY5TTVWMTN4R2V0UDlOb1ovNHhOYVp1MmhUUHh3
      PT0=
  become: true
  tasks:
    - name: check for update
      shell: '{{ ansible_facts[''pkg_mgr''] }} check-update -q --cve {{ insights_issues }}'
      check_mode: false
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100
      args:
        warn: false
    - when: check_out.rc == 100
      name: upgrade package
      shell: '{{ ansible_facts[''pkg_mgr''] }} upgrade -v -y --cve {{ insights_issues }}'
      args:
        warn: false
    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true

- name: ping
  hosts: '@@HOSTS@@'
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      T0tRVEpvU0hxM3pQMFpWYWU2bFF4SHJwYi9Dc0ltUThCQlR4VmVJajlHTi9jdXRhVDdsdGlNa1g3
      elhnelAyUHF0RkE0d1FrVVZzY1d4VXlZVUdGVjFJY2tmczhTemRDb21MdDVIeXpkYmpVQVVWV3Jl
      VXovOUR6eDFwMkQvclFsVDZyT1oyRmdGdWQ1dlBsOW0vaHRueEI1cXlSQVo4bUQrSjZBVlFhTEVx
      RGNqRlJVRU1YdVNIeWhkaUo5SVRjbUZPS0Q0bzJQV2dsYkJZTVNzQVZDZmNkNGtVNGpweXJSbEVy
      SGFIR1dBMzBacUxoZ1gyNkswTC9mYmphTUZWTlNaUnIvUy9qL3ZZZWY2VkJWcmxNK2FwV0Q2MERW
      TzFjZkVJZ3dKVVVkK1lTWGFNVW1IM3Y4UU9MU2QyZUVMalZ6dHJmbkNqVXBQNWdUUElpb0xwbjN3
      PT0=
  tasks:
    - ping: null
