- name: Reboot system (if applicable)
  hosts: newpreview,team-jupyter-server
  become: true
  gather_facts: false
  vars:
    insights_signature_exclude: /hosts,/vars
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS0NtbFJSWHBDUVVGQ1EwRkJa
      RVpwUlVWQmMzVTJTbWsxYkhoUlpqTlRkVTgyT1U0ek1WWXdZMUU1U1RCR1FXMUNVMGRyWTBGRFoy
      dFJPVTR6TVZZd1kxRUtPVWt6VGt4QlowRnJlbUo2Y1V4dWJEUkNNazB5TkN0cVRVNU9NMDlxVUU1
      b2RVdHRTREpQYTA5SFZHeDNjRzFUUWt0ak56ZFVRelkzUWs5cWJFRkJjQXB1U3pOT1ZXeFhXWGMy
      T0VwR2FVUlRka280YTNKaFluWmhOMGRxVlZFM2QwaHhlR0pFZUU5VGEwbHNZbWhaV1NzMFRFcHFk
      MHd2VGxkUVRVWnZhR050Q21nMGMwaFlVM0pNYWtVemIwUjJVR2RaWkVKdlpYaHRNMHRTVm5FeFNt
      Rk5RWHBSUlZad1MxZDVlRWhZZGxoNFZVbHFaMU51ZWl0ak9UTjFNM2gzWjFZS05taHdWbVprUW5S
      M1VWVTVSVXhHWlRGd2VqY3haRmMzVjBVeFZtcHpVRk5uVG5NeVIxZDFOV1JZU1ZaeVEzcGFUbUYy
      VG1SdlUxaDNUR3g1WTFKb09RcHBjbTlzUVdkcE5FVnNSRzl4VVRsYVdrcG5hRWREUTI5T04zRjZR
      VzFQZGtwdmN6QllaMnREVDJad1RWZ3ZZU3RTYkdSdlZqSmxXRUZWT1hCaGNHRmtDa3hLTVdKdVFt
      TXZiMlZWTVRNM1ZXRkRNWGxtYjNCV1JuZHdRVk5xWnowOUNqMVVVRzUxQ2kwdExTMHRSVTVFSUZC
      SFVDQlRTVWRPUVZSVlVrVXRMUzB0TFFvPQ==
  tasks:
    - when:
        - insights_needs_reboot is defined
        - insights_needs_reboot
      block:
        - name: Reboot system
          shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
          async: 1
          poll: 0
          ignore_errors: true
        - name: Wait for system to boot up
          local_action:
            module: wait_for
            host: '{{ hostvars[inventory_hostname][''ansible_host''] | default(hostvars[inventory_hostname][''ansible_ssh_host''],
              true) | default(inventory_hostname, true) }}'
            port: '{{ hostvars[inventory_hostname][''ansible_port''] | default(hostvars[inventory_hostname][''ansible_ssh_port''],
              true) | default(''22'', true) }}'
            delay: 15
            search_regex: OpenSSH
            timeout: 300
          become: false
