- name: run insights
  hosts: newpreview,team-jupyter-server
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS0NtbFJSWHBDUVVGQ1EwRkJa
      RVpwUlVWQmMzVTJTbWsxYkhoUlpqTlRkVTgyT1U0ek1WWXdZMUU1U1RCR1FXMUNVMGRyZDBGRFoy
      dFJPVTR6TVZZd1kxRUtPVWt4VkhCblowRnZXWE5xVmpsa2VUbE9VRXhJVW1SMFp6Um9UM1F2TVRS
      V01qY3JObE1ySzBKcU0yMTNWVFp6T1dSNmFTc3lTWFJCUkhKc04wUldPUXB5ZWxkd1NVdGFPWE5h
      UVVZMVlYUjJlRlI2T1cxRlNHZ3dMMGhFVVVkMWVTOWFVVUp0U1VFek1WTmljU3RuYTFrcmJqUlFP
      SEVyU0RSWWVHcE5iMlV4Q2xobGExTjJkbTR3VTNCaFVrc3liVFY1TURSU2NWRlFZbkpNVFU0d2VF
      RkNlVTAxZFU5QldIbFRWV2xFY0hZck5VOTFOM1JLYW5aaWREUndOVk5oV0cwS01YUTBkM0ZSTWts
      TFVsbDFhRkpuTjB4d1dFVldaWFZOZGpkTmJ6VlZWbFJPYlc1NE1VOW5ja05KU1hCQ2FXMXNNMFJy
      WWs1WVluZDFSVWRFUTJSa2NncEtTakowY3poSlV5dFdaakpOTDNZeVNqaG1RVkZLUVRoUVJFMTBU
      MGRIYWs5S05rSllXaTgxVVM4NWEwa3JUbkJIT1ZwVVRtWTBaR04yV1dGMlJFc3ZDa3gwVFdRM1lW
      Vk5hRTB5V1RaSlJFcFZZVkJ2VGxKVmFIbDNhbVpIWnowOUNqMWFaemRCQ2kwdExTMHRSVTVFSUZC
      SFVDQlRTVWRPUVZSVlVrVXRMUzB0TFFvPQ==
  become: true
  gather_facts: false
  tasks:
    - name: run insights
      command: insights-client
      changed_when: false
